-- CreateTable
CREATE TABLE `APPKEY` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `APPKEY` VARCHAR(191) NOT NULL,
    `MANDT` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `delrow` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MANDT` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `MANDT` VARCHAR(191) NOT NULL,
    `NAME` VARCHAR(191) NOT NULL,
    `DESCTN` VARCHAR(191) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `delrow` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `MANDT` VARCHAR(191) NOT NULL,
    `USRNME` VARCHAR(191) NOT NULL,
    `PSWRD` VARCHAR(191) NOT NULL,
    `EMAIL` VARCHAR(191) NOT NULL,
    `PHONE` VARCHAR(191) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `delrow` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
