-- CreateEnum
CREATE TYPE "MANDT_STATUS_ENUM" AS ENUM ('ACTIVE', 'INACTIVE', 'DELETED');

-- CreateEnum
CREATE TYPE "USER_STATUS_ENUM" AS ENUM ('ACTIVE', 'INACTIVE', 'DELETED');

-- CreateTable
CREATE TABLE "APPKEY" (
    "Id" SERIAL NOT NULL,
    "UUID" TEXT NOT NULL,
    "APPKEY" TEXT NOT NULL,
    "MANDT" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "delrow" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "APPKEY_pkey" PRIMARY KEY ("Id")
);

-- CreateTable
CREATE TABLE "MANDT" (
    "Id" SERIAL NOT NULL,
    "UUID" TEXT NOT NULL,
    "MANDT" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "DESCTN" TEXT NOT NULL,
    "STATUS" "MANDT_STATUS_ENUM" NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "delrow" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "MANDT_pkey" PRIMARY KEY ("Id")
);

-- CreateTable
CREATE TABLE "USER" (
    "Id" SERIAL NOT NULL,
    "UUID" TEXT NOT NULL,
    "MANDT" TEXT NOT NULL,
    "USRNME" TEXT NOT NULL,
    "PSWRD" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PHONE" TEXT NOT NULL,
    "STATUS" "USER_STATUS_ENUM" NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "delrow" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("Id")
);

-- CreateTable
CREATE TABLE "POLICIES" (
    "Id" SERIAL NOT NULL,
    "UUID" TEXT NOT NULL,
    "MANDT" TEXT NOT NULL,
    "POLICY" TEXT NOT NULL,
    "DESCTN" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "delrow" BOOLEAN NOT NULL DEFAULT false,
    "uSERId" INTEGER,

    CONSTRAINT "POLICIES_pkey" PRIMARY KEY ("Id")
);

-- CreateTable
CREATE TABLE "ROLES" (
    "Id" SERIAL NOT NULL,
    "UUID" TEXT NOT NULL,
    "MANDT" TEXT NOT NULL,
    "ROLE" TEXT NOT NULL,
    "DESCTN" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "delrow" BOOLEAN NOT NULL DEFAULT false,
    "policiesId" INTEGER,

    CONSTRAINT "ROLES_pkey" PRIMARY KEY ("Id")
);

-- CreateTable
CREATE TABLE "RIGHTS" (
    "Id" SERIAL NOT NULL,
    "UUID" TEXT NOT NULL,
    "MANDT" TEXT NOT NULL,
    "RIGHT" TEXT NOT NULL,
    "DESCTN" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "delrow" BOOLEAN NOT NULL DEFAULT false,
    "rolesId" INTEGER,

    CONSTRAINT "RIGHTS_pkey" PRIMARY KEY ("Id")
);

-- CreateIndex
CREATE UNIQUE INDEX "APPKEY_UUID_key" ON "APPKEY"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "APPKEY_APPKEY_key" ON "APPKEY"("APPKEY");

-- CreateIndex
CREATE UNIQUE INDEX "MANDT_UUID_key" ON "MANDT"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "MANDT_MANDT_key" ON "MANDT"("MANDT");

-- CreateIndex
CREATE UNIQUE INDEX "USER_UUID_key" ON "USER"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "USER_EMAIL_key" ON "USER"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "USER_PHONE_key" ON "USER"("PHONE");

-- CreateIndex
CREATE UNIQUE INDEX "USER_MANDT_USRNME_EMAIL_PHONE_key" ON "USER"("MANDT", "USRNME", "EMAIL", "PHONE");

-- CreateIndex
CREATE UNIQUE INDEX "POLICIES_UUID_key" ON "POLICIES"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "POLICIES_POLICY_key" ON "POLICIES"("POLICY");

-- CreateIndex
CREATE UNIQUE INDEX "POLICIES_MANDT_POLICY_key" ON "POLICIES"("MANDT", "POLICY");

-- CreateIndex
CREATE UNIQUE INDEX "ROLES_UUID_key" ON "ROLES"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "ROLES_ROLE_key" ON "ROLES"("ROLE");

-- CreateIndex
CREATE UNIQUE INDEX "ROLES_MANDT_ROLE_key" ON "ROLES"("MANDT", "ROLE");

-- CreateIndex
CREATE UNIQUE INDEX "RIGHTS_UUID_key" ON "RIGHTS"("UUID");

-- CreateIndex
CREATE UNIQUE INDEX "RIGHTS_RIGHT_key" ON "RIGHTS"("RIGHT");

-- CreateIndex
CREATE UNIQUE INDEX "RIGHTS_MANDT_RIGHT_key" ON "RIGHTS"("MANDT", "RIGHT");

-- AddForeignKey
ALTER TABLE "POLICIES" ADD CONSTRAINT "POLICIES_uSERId_fkey" FOREIGN KEY ("uSERId") REFERENCES "USER"("Id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROLES" ADD CONSTRAINT "ROLES_policiesId_fkey" FOREIGN KEY ("policiesId") REFERENCES "POLICIES"("Id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RIGHTS" ADD CONSTRAINT "RIGHTS_rolesId_fkey" FOREIGN KEY ("rolesId") REFERENCES "ROLES"("Id") ON DELETE SET NULL ON UPDATE CASCADE;
