version: '3'

services:
  database:
    image: mysql:8.0.36
    container_name: database-production
    env_file: ../../.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ROOT_AUTHENTICATION_PLUGIN: caching_sha2_password
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}']
      interval: 15s
      timeout: 10s
      retries: 5
  app:
    stdin_open: true
    tty: true
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    env_file: ../../.env
    environment:
      - PORT=3000
      - NODE_ENV=production
    container_name: 'axzy-manager-${APP_VERSION}'
    volumes:
      - ../../logs:/code/logs
    depends_on:
      database:
        condition: service_healthy
